simulation:
  max_steps: 1000
  time_step_penalty: -0.01
  collision_penalty: -0.1
  failure_penalty: -0.01
  expired_penalty: 2.0
  success_reward: 20.0
  subgoal_reward: 1.0
  pickup_multiplier: 1.0
  place_multiplier: 2.0
  retrieve_multiplier: 2.0
  max_inventory: 1
  max_orders: 3
  order_ttl: 120
  order_spawn_rate: 0.4

grid:
  width: 9
  height: 9
  # Notice the "island" of stations/walls in the middle!
  layout_str: |
    #########
    #S.....S#
    #.......#
    #..###..#
    #..#.#..#
    #..###..#
    #.......#
    #D.....T#
    #########
  start_pos: [1, 4]
  stations:
    potato_source: {x: 1, y: 1, type: source, name: PotatoBin, item_id: 1}
    tomato_source: {x: 7, y: 1, type: source, name: TomatoBin, item_id: 3}
    garbage_source: {x: 7, y: 7, type: trash, name: GarbageBin, item_id: 0}
    stove: {x: 3, y: 4, type: process, name: Stove}
    cutboard: {x: 5, y: 4, type: process, name: CutBoard}
    delivery: {x: 1, y: 7, type: delivery, name: ServiceWindow}

items:
  0: "Empty"
  1: "RawPotato"
  2: "CookedPotato"
  3: "RawTomato"
  4: "SlicedTomato"

recipes:
  - input: 1
    station: "Stove"
    output: 2
    time: 15
  - input: 3
    station: "CutBoard"
    output: 4
    time: 8